apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azureidentities.aadpodidentity.k8s.io
  annotations:
    api-approved.kubernetes.io: "https://github.com/kubernetes/enhancements/pull/1111"
spec:
  group: aadpodidentity.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                clientID:
                  type: string
                resourceID:
                  type: string
  scope: Namespaced
  names:
    plural: azureidentities
    singular: azureidentity
    kind: AzureIdentity
    shortNames:
    - azid

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azureidentitybindings.aadpodidentity.k8s.io
  annotations:
    api-approved.kubernetes.io: "https://github.com/kubernetes/enhancements/pull/1111"
spec:
  group: aadpodidentity.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                azureIdentity:
                  type: string
                selector:
                  type: string
  scope: Namespaced
  names:
    plural: azureidentitybindings
    singular: azureidentitybinding
    kind: AzureIdentityBinding
    shortNames:
    - azidbinding