# filepath: manifests/prohibited-target-crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azureingressprohibitedtargets.appgw.ingress.k8s.io
spec:
  group: appgw.ingress.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                hostname:
                  type: string
                namespace:
                  type: string
  scope: Namespaced
  names:
    plural: azureingressprohibitedtargets
    singular: azureingressprohibitedtarget
    kind: AzureIngressProhibitedTarget
    shortNames:
    - aipt