apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    server: {{ .Values.acme_server }}
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: letsencrypt-dns-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: {{ .Values.dns_credentials_secret }}
              key: api-token
            zoneID: {{ .Values.cloudflare_zone_id }}